name: panel
channels:
  - conda-forge
dependencies:
  - python
  - dask
  - datashader
  - geopandas
  - holoviews
  - hvplot
  - jupyterlab=3
  - jupyter-panel-proxy
  - panel
  - rasterio
  - rioxarray
  - xarray
